### ISSUE TITLE
Add alert banners for system wide alerts

### ISSUE THREAD

**Issue by melmai** [melmai/kcalerts-restapi#42]
The current version requires alerts to be associated with a route to display. System wide alerts do not have this. Will need to implement banners to display on the home page for System alerts.

Example:
`{
      "alert_id": 1713,
      "effect_name": "Snow Routes",
      "effect": "DETOUR",
      "cause_name": "snow",
      "cause": "WEATHER",
      "header_text": "Snow is falling across King County, but Metro buses are currently able to operate on their regular routes. Transit Alerts will be sent out if there is a need to switch to snow routes.",
      "short_header_text": "Snow is falling across King County, but Metro buses are regular operation",
      "url": "https://kingcountymetro.blog/",
      "severity": "Significant",
      "created_dt": "1670339549",
      "last_modified_dt": "1670428019",
      "service_effect_text": "Bus, Marine and Rail service is operating on snow routes.",
      "alert_lifecycle": "New",
      "banner_text": "Snow is falling across King County, but Metro buses are currently able to operate on their regular routes. Transit Alerts will be sent out if there is a need to switch to snow routes.",
      "effect_periods": [{ "effect_start": "1670339520", "effect_end": "" }],
      "affected_services": {
        "services": [
          { "route_type": "0", "mode_name": "Light Rail" },
          { "route_type": "3", "mode_name": "Bus" },
          { "route_type": "4", "mode_name": "Boat" }
        ],
        "elevators": []
      }
    }
`

**Comment by melmai** [comment]
It looks like Alert ID #1714 is also a systemwide alert, and likely more recently published based on ID. However, it does not have a `banner_text` field. Should I only feature ones that have `banner_text` as a field, and ignore any other system alerts?

`{
      "alert_id": 1714,
      "effect_name": "Snow Routes",
      "effect": "DETOUR",
      "cause_name": "snow",
      "cause": "WEATHER",
      "header_text": "All bus routes in Metro’s North King County snow area are currently operating on their designated snow routing and may also be delayed.",
      "short_header_text": "All Rts in Metro's North King Cty snow area are on their snow routing.",
      "url": "https://kingcounty.gov/depts/transportation/metro/alerts-updates/service-advisories/snow-ice-flood-alerts.aspx ",
      "severity": "Significant",
      "created_dt": "1670340085",
      "last_modified_dt": "1670340085",
      "service_effect_text": "Bus service is operating on snow routes.",
      "alert_lifecycle": "New",
      "effect_periods": [{ "effect_start": "1670340057", "effect_end": "" }],
      "affected_services": {
        "services": [{ "route_type": "3", "mode_name": "Bus" }],
        "elevators": []
      }
    }`

**Comment by markbilodeau-metroweb** [comment]
The alert banner on the home page should only appear when `banner_text` is found in the feed. If there happens to be 2 or more alerts with `banner_text` then the most current one is displayed and all others are ignored. In other words, we only display the most recent alert.

**Comment by melmai** [comment]
Created bootstrap banners and merged to dev
